:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:scheduler:
  :schedule:
    abandoned_cart:
      cron: "*/30 * * * *"
      class: "MarkCartAsAbandonedJob"
